import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
import { Roboto } from "next/font/google";
import localFont from "next/font/local";

const soehne = localFont({
  src: [
    {
      path: "./fonts/TestSöhne-Leicht.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/TestSöhne-Buch.otf",
      weight: "500",
      style: "medium",
    },

    {
      path: "./fonts/TestSöhne-Kräftig.otf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "./fonts/TestSöhne-Halbfett.otf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={soehne.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
